// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-QJPweJLYV4lU2EZYvDa8im9jGqiCIQQ',
    appId: '1:84409725538:web:986c32f86b53bf1d70973b',
    messagingSenderId: '84409725538',
    projectId: 'spiceshub-d8f87',
    authDomain: 'spiceshub-d8f87.firebaseapp.com',
    storageBucket: 'spiceshub-d8f87.firebasestorage.app',
    measurementId: 'G-FP7396467T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoZmwinPDMBncYLg79bB1rK9KQZrXmd6o',
    appId: '1:84409725538:android:91dd940f031c38e270973b',
    messagingSenderId: '84409725538',
    projectId: 'spiceshub-d8f87',
    storageBucket: 'spiceshub-d8f87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3u2KKH9_LRrMospt1hS1OFgPvSRFi_Z0',
    appId: '1:84409725538:ios:5d67edcef36fdc1370973b',
    messagingSenderId: '84409725538',
    projectId: 'spiceshub-d8f87',
    storageBucket: 'spiceshub-d8f87.firebasestorage.app',
    iosBundleId: 'com.example.spicesHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3u2KKH9_LRrMospt1hS1OFgPvSRFi_Z0',
    appId: '1:84409725538:ios:5d67edcef36fdc1370973b',
    messagingSenderId: '84409725538',
    projectId: 'spiceshub-d8f87',
    storageBucket: 'spiceshub-d8f87.firebasestorage.app',
    iosBundleId: 'com.example.spicesHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-QJPweJLYV4lU2EZYvDa8im9jGqiCIQQ',
    appId: '1:84409725538:web:88d96068034cd83770973b',
    messagingSenderId: '84409725538',
    projectId: 'spiceshub-d8f87',
    authDomain: 'spiceshub-d8f87.firebaseapp.com',
    storageBucket: 'spiceshub-d8f87.firebasestorage.app',
    measurementId: 'G-P388F7S3HF',
  );
}
